#!/bin/bash

objDir=$WM_PROJECT_DIR/wmake
if [ -d $objDir ]
then
    chmod +x ./ofCmakeConfig
    chmod +x ./occ
    rm -f $objDir/ofCmakeConfig $objDir/occ
    cp  ofCmakeConfig occ wmakelog2cmakelists.py $objDir/
    echo "installed ofCmakeConfig"
else
    echo "please active OpenFOAM environment"
fi
